version = "3.7.10"

runner.dialect = scala3

maxColumn = 100
indent.main = 2
indent.defnSite = 2

align.preset = most
align.multiline = false

rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  SortModifiers,
  PreferCurlyFors
]

newlines.source = keep
newlines.topLevelStatementBlankLines = [
  {
    blanks = 1
  }
]
