include: package:lints/recommended.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  
  errors:
    missing_required_param: error
    missing_return: error
    dead_code: warning
    unused_import: warning
    unused_local_variable: warning

  exclude:
    - build/**
    - lib/generated/**

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - avoid_types_as_parameter_names
    - prefer_const_constructors
    - prefer_final_fields
    - prefer_single_quotes
    - require_trailing_commas
    - sort_constructors_first
    - use_key_in_widget_constructors
