source 'https://rubygems.org'

ruby '3.2.0'

gem 'sinatra', '~> 3.1'
gem 'puma', '~> 6.4'
gem 'pg', '~> 1.5'
gem 'sequel', '~> 5.75'
gem 'redis', '~> 5.0'
gem 'mail', '~> 2.8'
gem 'twilio-ruby', '~> 6.9'
gem 'dotenv', '~> 2.8'
gem 'rack-cors', '~> 2.0'
gem 'json', '~> 2.7'

group :development do
  gem 'rerun', '~> 0.14'
end
